New features and pages added
gisachris/hello-world pull request #1
Opened 2023-03-21 14:55 UTC by gisachris

Hello @levy002 
In This PR I have included:
An updated html file
An updated css file
An ignored test.md file
Updated Fully working html & css linters
Updated the readme file

2023-03-21 15:27 UTC, levy002 requested changes
## Hello @gisachris   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ]  Kindly make sure to update your PR description by providing a more detailed PR description. It makes your repo looks more professional. wink

   - Example of good PR
![image](https://user-images.githubusercontent.com/87197412/184990532-da778ab4-c789-4136-90a9-629eedd969da.png)

- [ ] Kindly make sure to solve all Linters errors in all linter checks. All Linters check must pass and looks green.

   - ### YOUR LINTER CHECKS
    ![image](https://user-images.githubusercontent.com/87197412/226653810-4a2f1b6b-21c0-4e7e-b999-330a537b3d97.png)

   - ### CORRECT LINTERS CHECKS
     ![image](https://user-images.githubusercontent.com/87197412/226653973-0fcd167e-3339-469a-88bd-e62eaab3a8ea.png)

  
- [ ] Kindly make sure to remove the `test.md` file which must not be represented in your repository in order to meet the project requirements. This file was ignored by git so it must be represented in the repository. Kindly remove it. :wink: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Kindly make sure to write your commit message in the imperative tense and capitalized it. Please check this [lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to understand it clearly.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 08:53 UTC, LionRouge1 requested changes
Hi @gisachris, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![so close](https://media.giphy.com/media/qLWdMYX1NYF2g/giphy.gif)
![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)
## Suggested changes
- [ ] As mentioned in the previous review, Kindly make sure to solve all Linters errors in all linter checks. All Linters check must pass and looks green. Before it was just some linters errors that were needed to be fix but after your changes, the GitHub action is not working at all, please check that.

- [ ] Please add an HTML file that includes a header with the text "Hello Microverse!". Use  `<h1>` tag as required in the project requirement. This file was actually removed after the first review kindly add it back it part of the project requirement. (Please you should rather remove the test.md file) 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Please your PR summary should be addressed to everybody, not only to a particular Code reviewer. The PR summary helps other developers, code reviewers or visiters know what to expect from the branch.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-23 08:53 UTC, LionRouge1 commented on README.md
- [ ] As mentioned in the previous review, Please instead of just coping and pasting the README template provided, kindly follow these steps in order to make your README file professional and more attractive:
- Customize the template to suit your project by removing all comments and all instructions on how it must be filled and adding your project-related information.
- Since you didn't deploy the project, it will be nice to remove the live Demo section.
- Kindly remove the section description, i.e. "> Describe the tech stack and include only the relevant sections that apply to your project. and filled in with their custom content.
- Please remove all sections that are not relevant to your project to avoid having broken links in your README

2023-03-23 08:53 UTC, LionRouge1 commented on .gitignore
> +text.md
- [ ] Please add `test.md` to your `.gitignore` file in order to make the Git system ignore the file.

2023-03-23 08:53 UTC, LionRouge1 commented on test.md
- [ ] As mentioned in the previous review, Kindly make sure to remove the `test.md` file which must not be represented in your repository in order to meet the project requirements. But it same as you removed the `index.html` instead of `test.md` :smile:

2023-03-23 11:58 UTC, closed without merging